# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{orientdb-ar}
  s.version = "0.0.5"
  s.platform = %q{jruby}

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.6") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Adrian Madrid}]
  s.date = %q{2012-01-12}
  s.description = %q{Active Model wrappers to persist Ruby objects under OrientDB in JRuby.}
  s.email = [%q{aemadrid@gmail.com}]
  s.executables = [%q{orientdbar_console}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gemspec",
    ".gitignore",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/orientdbar_console",
    "lib/orientdb-ar.rb",
    "lib/orientdb-ar/attributes.rb",
    "lib/orientdb-ar/base.rb",
    "lib/orientdb-ar/conversion.rb",
    "lib/orientdb-ar/document_mixin.rb",
    "lib/orientdb-ar/embedded.rb",
    "lib/orientdb-ar/ext.rb",
    "lib/orientdb-ar/relations.rb",
    "lib/orientdb-ar/relations/embedds_many.rb",
    "lib/orientdb-ar/relations/embedds_one.rb",
    "lib/orientdb-ar/relations/links_many.rb",
    "lib/orientdb-ar/relations/links_one.rb",
    "lib/orientdb-ar/sql.rb",
    "lib/orientdb-ar/sql/delete.rb",
    "lib/orientdb-ar/sql/insert.rb",
    "lib/orientdb-ar/sql/query.rb",
    "lib/orientdb-ar/sql/update.rb",
    "orientdb-ar.gemspec",
    "spec/base_spec.rb",
    "spec/dirty_spec.rb",
    "spec/lint_behavior.rb",
    "spec/lint_spec.rb",
    "spec/model_spec.rb",
    "spec/models/address.rb",
    "spec/models/customer.rb",
    "spec/models/flo_admin.rb",
    "spec/models/invoice.rb",
    "spec/models/invoice_line.rb",
    "spec/models/person.rb",
    "spec/models/phone_number.rb",
    "spec/models/product.rb",
    "spec/models/simple_person.rb",
    "spec/serialization_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://rubygems.org/gems/orientdb}
  s.require_paths = [%q{lib}]
  s.rubyforge_project = %q{orientdb-ar}
  s.rubygems_version = %q{1.8.9}
  s.summary = %q{ActiveRecord-like persistency through OrientDB in JRuby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<orientdb>, [">= 0.0.20"])
      s.add_runtime_dependency(%q<activemodel>, [">= 3.0.3"])
      s.add_runtime_dependency(%q<jnunemaker-validatable>, ["= 1.8.4"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.4"])
    else
      s.add_dependency(%q<orientdb>, [">= 0.0.20"])
      s.add_dependency(%q<activemodel>, [">= 3.0.3"])
      s.add_dependency(%q<jnunemaker-validatable>, ["= 1.8.4"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.4"])
    end
  else
    s.add_dependency(%q<orientdb>, [">= 0.0.20"])
    s.add_dependency(%q<activemodel>, [">= 3.0.3"])
    s.add_dependency(%q<jnunemaker-validatable>, ["= 1.8.4"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.4"])
  end
end

